---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
  labels:
    app: nginx
    layer: frontend
        
spec:

  type: LoadBalancer
  selector:
    
    app: nginx

  ports:
    - nodePort: 30063
      port: 80
      targetPort: 80
